services:
  mypythonapp:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1